package:
  name: jarvis_cd
  version: 0.0.0

source:
  git_url: https://github.com/iowarp/platform-plugins-interface
  git_depth: 1

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - iowarp::jarvis_util    

files:
  - README.md

test:
  requires:
    - pyaml
    - pandas
    - iowarp::jarvis_util
  imports:
    - jarvis_cd


about:
  home: https://grc.iit.edu/research/projects/iowarp/
  license: BSD
  summary: IOWarp Jarvis CD Conda Package
