name: conda

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
      - name: build-conda
        run: |
          conda install -y conda-build
          conda install -y conda-verify
          conda install -y anaconda-client
          conda-build recipe
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: config-x64-linux-out.log
          path: /usr/share/miniconda/envs/test/conda-bld/jarvis_cd-0.0.0-py311_0.tar.bz2
