name: main

on:
  # push:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled'
        required: false
        default: false
env:
  BUILD_TYPE: Debug
  LOCAL: local

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Get Sources
        uses: actions/checkout@v4

      - name: Install Apt Dependencies
        run: bash ci/install_deps.sh

      - name: Install Jarvis
        run: bash ci/install_jarvis.sh

      - name: Run pylint
        run: bash ci/lint.sh

      - name: Test
        run: bash ci/run_tests.sh

#      - name: Coveralls
#        uses: coverallsapp/github-action@master
#        with:
#          path-to-lcov: lcov.info
#          github-token: ${{ secrets.GITHUB_TOKEN }}
